### ISSUE TITLE
Using kalman filter for smoother bounding boxes

### ISSUE THREAD

**Issue by keerti-ds** [akash-agni/Real-Time-Object-Detection#4]
Hi, 

I would like to know if there is a possibility to use tracker(like kalam filter) in this? 
I have these fluctuating bounding boxes (not of the same size) and I want to stable them and also track them. I am new to Pytorch and I find it quite confusing to use it with this script? Could you give me some hints or suggestions on how I should proceed further?

https://github.com/akash-agni/Real-Time-Object-Detection/blob/e74d63151b1c58ccff79d6b178d6cf2244551daa/Object_Detection_Youtube.py#L62

**Comment by akash-agni** [comment]
I am guessing you meant Kalman filters.
Yeah it is possible and their is actually a really cool implementation of this <a href="https://github.com/abewley/sort/blob/master/sort.py">here</a> by <a href="https://github.com/abewley">abewley</a>.
