### ISSUE TITLE
Drone_Human_Detection_Model.py code just detect human not anything else

### ISSUE THREAD

**Issue by milad-s5** [akash-agni/Real-Time-Object-Detection#5]
I test your code and it just detect humans. It can't detect cars or trucks.
![image](https://user-images.githubusercontent.com/82322980/158791137-318f9bd1-7934-475a-b883-3c03d4d02c6b.png)

**Comment by akash-agni** [comment]
Well that is the point for the code, it says "Drone Human Detection". Please use object detection model file for other objects.
